# https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx

controller:
  config:
    # Preserve source ip
    use-forwarded-headers: true

  # Resources limitations/reservations
  resources:
    requests:
      cpu: 100m      #  a affiniter selon la taille du cluster (voir la consommation du pod ingress via prometheus)
      memory: 90Mi # idem
    limits:
      cpu: 500m #  idem
      memory: 120Mi  # idem

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - ingress-nginx
          topologyKey: kubernetes.io/hostname

  # high availability
  replicaCount: 2

  # Default ingress
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true

  service:
    # Needed annotations for AWS
    # annotations:
    #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    externalTrafficPolicy: Local



Installation:.
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm install ingress-nginx  ingress-nginx/ ingress-nginx –namespace  ingress-nginx –create-namespace -f  ingress-nginx-config.yml


# kubernetes/chapitres/15/ingress-nginx-config.yaml at master · EditionsENI/kubernetes · GitHub
